"""
WatchDawg PIN Lock Authentication Router.

Endpoints:
- POST /auth/unlock   — Validate PIN, issue an in-memory session token.
- POST /auth/lock     — Immediately invalidate the caller's session token.
- GET  /auth/status   — Return whether PIN lock is enabled and if a token is valid.

Security model:
- A single PIN is read from WATCHDAWG_PIN in .env.
- If WATCHDAWG_PIN is not set, locking is disabled — all content is visible.
- Valid tokens are stored in a module-level Python set (in-memory only).
- The set is never persisted to disk. Container restart clears all sessions.
- Tokens are 32-byte URL-safe random strings generated by secrets.token_urlsafe().
- The X-WatchDawg-Token header is the sole mechanism for passing the token.
- This module exposes is_unlocked(token) for use by other routers.
"""

import logging
import secrets

from fastapi import APIRouter, Header, HTTPException
from typing import Optional

from app.config import settings

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/auth", tags=["auth"])

# ---------------------------------------------------------------------------
# In-memory token store — cleared on every container restart by design.
# A set is used so multiple browser tabs can each hold their own token
# and any one of them can lock without affecting others.
# ---------------------------------------------------------------------------
_valid_tokens: set[str] = set()


# ---------------------------------------------------------------------------
# Public helper used by feed.py, favorite.py, library.py, channel.py
# ---------------------------------------------------------------------------
def is_unlocked(token: Optional[str]) -> bool:
    """
    Return True if either:
      a) PIN locking is not configured (WATCHDAWG_PIN not set), or
      b) The supplied token is present in the valid token set.

    Returns False if locking is configured and the token is absent or invalid.
    """
    if not settings.watchdawg_pin:
        # Locking disabled — treat everything as unlocked
        return True
    if token and token in _valid_tokens:
        return True
    return False


def pin_lock_enabled() -> bool:
    """Return True if a PIN has been configured."""
    return bool(settings.watchdawg_pin)


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------

@router.post("/unlock")
async def unlock(
    pin: str,
    x_watchdawg_token: Optional[str] = Header(None),
):
    """
    Validate the PIN and return a session token on success.

    The returned token must be sent as the X-WatchDawg-Token header on all
    subsequent requests that require unlocked content.

    If PIN locking is not configured, returns a success response immediately
    without issuing a real token (all content is always visible).
    """
    if not settings.watchdawg_pin:
        logger.info("PIN unlock called but WATCHDAWG_PIN is not set — locking disabled.")
        return {
            "status": "unlocked",
            "token": None,
            "message": "PIN lock is not configured. All content is visible.",
        }

    # Use secrets.compare_digest to prevent timing attacks
    if not secrets.compare_digest(pin, settings.watchdawg_pin):
        logger.warning("PIN unlock attempt failed — incorrect PIN.")
        raise HTTPException(status_code=401, detail="Incorrect PIN.")

    token = secrets.token_urlsafe(32)
    _valid_tokens.add(token)
    logger.info(f"PIN unlock successful. Active sessions: {len(_valid_tokens)}")

    return {
        "status": "unlocked",
        "token": token,
        "message": "Session unlocked. Send X-WatchDawg-Token header on future requests.",
    }


@router.post("/lock")
async def lock(
    x_watchdawg_token: Optional[str] = Header(None),
):
    """
    Immediately invalidate the caller's session token.

    After calling this, the client must call /auth/unlock again with a valid
    PIN to regain access to locked content.
    """
    if not settings.watchdawg_pin:
        return {"status": "locked", "message": "PIN lock is not configured."}

    if x_watchdawg_token and x_watchdawg_token in _valid_tokens:
        _valid_tokens.discard(x_watchdawg_token)
        logger.info(f"Session token revoked. Active sessions: {len(_valid_tokens)}")
        return {"status": "locked", "message": "Session token revoked."}

    # Token wasn't valid anyway — still return success (idempotent)
    return {"status": "locked", "message": "No active session to revoke."}


@router.get("/status")
async def auth_status(
    x_watchdawg_token: Optional[str] = Header(None),
):
    """
    Return the current PIN lock state.

    Used by the browser UI on page load to decide whether to show the PIN
    input bar and what state the padlock icon should display.
    """
    enabled = pin_lock_enabled()
    unlocked = is_unlocked(x_watchdawg_token)

    return {
        "pin_lock_enabled": enabled,
        "is_unlocked": unlocked,
        # Never echo the token back — only confirm whether it's valid
    }
