"""
WatchDawg Library Router.

Serves the local NAS /music_videos directory as a browsable media library.
All files here are streamable directly — no yt-dlp resolution needed.

Endpoints:
- GET    /library                           — List all video files (recursive).
- GET    /library/stream/{filename:path}    — Stream a local file (range-capable).
- GET    /library/thumb/{filename:path}     — Serve a generated thumbnail jpg.
- POST   /library/generate-thumbnails       — ffmpeg frame-grab for unmatched files.
- DELETE /library/file                      — Delete file + add to skip list.
"""

import asyncio
import logging
import os
import subprocess
import urllib.parse
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import FileResponse
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db_session
from app.models import Favorite, Video, SkipListEntry
from app.config import settings
from app.encryption import encrypt_value
from app.hashing import hmac_hash

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/library", tags=["library"])

VIDEO_EXTENSIONS = {".mp4", ".mkv", ".webm", ".m4v", ".avi", ".mov"}
THUMB_SUFFIX = ".watchdawg_thumb.jpg"
FFMPEG_GRAB_SECOND = 5  # Grab frame at 5 seconds into the video


def _human_size(size_bytes: int) -> str:
    for unit in ("B", "KB", "MB", "GB"):
        if size_bytes < 1024:
            return f"{size_bytes:.1f} {unit}"
        size_bytes /= 1024
    return f"{size_bytes:.1f} TB"


def _safe_real_path(relative_path: str, music_dir: str) -> str:
    """Resolve relative path safely — raises 400 on path traversal attempt."""
    joined = os.path.join(music_dir, relative_path)
    real_path = os.path.realpath(joined)
    real_dir = os.path.realpath(music_dir)
    if not real_path.startswith(real_dir + os.sep):
        raise HTTPException(status_code=400, detail="Invalid file path")
    return real_path


def _thumb_path_for(video_path: str) -> str:
    """Return the sidecar thumbnail path for a given video file path."""
    return video_path + THUMB_SUFFIX


def _generate_thumb_sync(video_path: str, thumb_path: str) -> bool:
    """
    Run ffmpeg to grab a single frame at FFMPEG_GRAB_SECOND seconds.
    Returns True on success, False on failure.
    Runs synchronously — call via asyncio.to_thread() in async context.
    """
    cmd = [
        "ffmpeg",
        "-ss", str(FFMPEG_GRAB_SECOND),
        "-i", video_path,
        "-frames:v", "1",
        "-q:v", "4",           # JPEG quality (2=best, 31=worst; 4 is a good balance)
        "-vf", "scale=480:-1", # Resize to 480px wide, keep aspect ratio
        "-y",                  # Overwrite if exists
        thumb_path,
    ]
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            timeout=30,
        )
        if result.returncode == 0 and os.path.isfile(thumb_path):
            return True
        logger.warning(
            f"ffmpeg failed for {video_path}: "
            f"{result.stderr.decode(errors='replace')[:200]}"
        )
        return False
    except subprocess.TimeoutExpired:
        logger.warning(f"ffmpeg timed out for {video_path}")
        return False
    except Exception as e:
        logger.warning(f"ffmpeg error for {video_path}: {e}")
        return False


@router.get("")
async def list_library(
    db: AsyncSession = Depends(get_db_session),
):
    """
    Recursively scan /music_videos and return all video files.

    Each file includes a 'subfolder' field with the immediate parent directory
    name relative to the music root (empty string for root-level files).
    The sidebar filter in the UI uses this field to group files by folder.

    For files with a DB record (Favorite), uses the stored thumbnail_url.
    For manually-added files, checks for a sidecar .watchdawg_thumb.jpg
    generated by /library/generate-thumbnails and serves it via
    /library/thumb/{relative_path}.
    """
    music_dir = settings.music_videos_path

    if not os.path.isdir(music_dir):
        return {"total": 0, "files": [], "directory": music_dir}

    # Build DB enrichment lookup by basename
    stmt = (
        select(Favorite, Video)
        .join(Video, Favorite.video_id == Video.id)
        .where(Favorite.local_file_path.isnot(None))
    )
    result = await db.execute(stmt)
    rows = result.all()

    known_files: dict[str, tuple] = {}
    for fav, video in rows:
        if fav.local_file_path:
            basename = os.path.basename(fav.local_file_path)
            known_files[basename] = (fav, video)

    files = []

    for dirpath, _dirnames, filenames in os.walk(music_dir):
        for filename in sorted(filenames):
            # Skip our own thumbnail sidecar files
            if filename.endswith(THUMB_SUFFIX):
                continue
            _, ext = os.path.splitext(filename)
            if ext.lower() not in VIDEO_EXTENSIONS:
                continue

            full_path = os.path.join(dirpath, filename)
            relative_path = os.path.relpath(full_path, music_dir)

            try:
                stat = os.stat(full_path)
            except OSError:
                continue

            # subfolder: the top-level directory name under music_dir.
            # e.g. music_dir/Pop Music Videos/song.mp4 -> subfolder = "Pop Music Videos"
            # e.g. music_dir/song.mp4 -> subfolder = "" (root level)
            path_parts = relative_path.split(os.sep)
            subfolder = path_parts[0] if len(path_parts) > 1 else ""

            match = known_files.get(filename)
            if match:
                fav, video = match
                title = video.title
                artist = video.artist
                thumbnail_url = video.thumbnail_url
                favorite_id = fav.id
                video_id = video.id
            else:
                title = os.path.splitext(filename)[0]
                artist = None
                favorite_id = None
                video_id = None
                # Check for a sidecar thumbnail generated by ffmpeg
                thumb_path = _thumb_path_for(full_path)
                if os.path.isfile(thumb_path):
                    thumb_rel = os.path.relpath(thumb_path, music_dir)
                    thumbnail_url = f"/library/thumb/{urllib.parse.quote(thumb_rel, safe='/')}"
                else:
                    thumbnail_url = None

            files.append({
                "filename": filename,
                "relative_path": relative_path,
                "subfolder": subfolder,          # top-level folder name (empty = root)
                "title": title,                  # clean title without subfolder prefix
                "artist": artist,
                "thumbnail_url": thumbnail_url,
                "size_bytes": stat.st_size,
                "size_human": _human_size(stat.st_size),
                "modified_at": stat.st_mtime,
                "stream_url": f"/library/stream/{urllib.parse.quote(relative_path, safe='/')}",
                "favorite_id": favorite_id,
                "video_id": video_id,
            })

    files.sort(key=lambda f: f["modified_at"], reverse=True)

    logger.info(f"Library scan: {len(files)} video files in {music_dir} (recursive)")
    return {
        "total": len(files),
        "directory": music_dir,
        "files": files,
    }


@router.post("/generate-thumbnails")
async def generate_thumbnails(
    limit: int = Query(20, ge=1, le=200, description="Max files to process per run"),
):
    """
    Generate thumbnail images for library files that have no thumbnail.

    Scans /music_videos recursively for video files that have no sidecar
    .watchdawg_thumb.jpg file. For each, runs ffmpeg to grab a frame at
    5 seconds and saves it alongside the video. The library scan then
    picks these up automatically and serves them via /library/thumb/.

    Only processes files with no DB record (manually-added files) since
    WatchDawg downloads already get thumbnails from the source platform.
    Capped per run to avoid long blocking — run multiple times for full coverage.
    """
    music_dir = settings.music_videos_path
    if not os.path.isdir(music_dir):
        return {"status": "error", "detail": "Library directory not found"}

    # Build set of DB-known basenames so we skip them (they have source thumbnails)
    candidates = []
    for dirpath, _dirnames, filenames in os.walk(music_dir):
        for filename in filenames:
            if filename.endswith(THUMB_SUFFIX):
                continue
            _, ext = os.path.splitext(filename)
            if ext.lower() not in VIDEO_EXTENSIONS:
                continue
            full_path = os.path.join(dirpath, filename)
            thumb_path = _thumb_path_for(full_path)
            if not os.path.isfile(thumb_path):
                candidates.append((full_path, thumb_path))
            if len(candidates) >= limit:
                break
        if len(candidates) >= limit:
            break

    summary = {"total": len(candidates), "generated": 0, "failed": 0}

    for video_path, thumb_path in candidates:
        success = await asyncio.to_thread(_generate_thumb_sync, video_path, thumb_path)
        if success:
            summary["generated"] += 1
            logger.info(f"Generated thumbnail: {thumb_path}")
        else:
            summary["failed"] += 1
        await asyncio.sleep(0.1)

    logger.info(
        f"Thumbnail generation complete: {summary['generated']} generated, "
        f"{summary['failed']} failed out of {summary['total']}"
    )
    return {"status": "complete", "summary": summary}


@router.get("/thumb/{filename:path}")
async def serve_thumbnail(filename: str):
    """Serve a generated sidecar thumbnail jpg."""
    music_dir = settings.music_videos_path
    real_path = _safe_real_path(filename, music_dir)

    if not os.path.isfile(real_path):
        raise HTTPException(status_code=404, detail="Thumbnail not found")

    return FileResponse(path=real_path, media_type="image/jpeg")


@router.delete("/file")
async def delete_library_file(
    relative_path: str = Query(..., description="Relative path of the file within the library"),
    db: AsyncSession = Depends(get_db_session),
):
    """
    Delete a video file from the NAS library directory.

    Full delete flow:
    1. Validates path stays within music_videos (no path traversal).
    2. Looks up the associated Video record via the Favorite link.
    3. Adds the video's source_post_id to the skip list so it won't
       reappear on future channel scrapes.
    4. Deletes the Favorite and Video DB records.
    5. Deletes the actual file and any sidecar thumbnail from disk.
    """
    music_dir = settings.music_videos_path
    real_path = _safe_real_path(relative_path, music_dir)

    if not os.path.isfile(real_path):
        raise HTTPException(status_code=404, detail=f"File not found: {relative_path}")

    filename = os.path.basename(real_path)
    skip_added = False
    favorite_cleaned = False
    video_deleted = False

    # Find Favorite record by exact path or basename match
    fav_stmt = select(Favorite).where(Favorite.local_file_path == real_path)
    fav_result = await db.execute(fav_stmt)
    favorite = fav_result.scalar_one_or_none()

    if favorite is None:
        all_favs_result = await db.execute(
            select(Favorite).where(Favorite.local_file_path.isnot(None))
        )
        for fav in all_favs_result.scalars().all():
            if os.path.basename(fav.local_file_path or "") == filename:
                favorite = fav
                break

    if favorite is not None:
        video_stmt = select(Video).where(Video.id == favorite.video_id)
        video_result = await db.execute(video_stmt)
        video = video_result.scalar_one_or_none()

        if video is not None:
            post_hash = hmac_hash(video.source_post_id)
            existing_skip = await db.execute(
                select(SkipListEntry).where(
                    SkipListEntry.source_post_id_hash == post_hash
                )
            )
            if existing_skip.scalar_one_or_none() is None:
                db.add(SkipListEntry(
                    source_post_id_encrypted=encrypt_value(video.source_post_id),
                    source_post_id_hash=post_hash,
                    source_provider=video.source_provider,
                ))
                skip_added = True
                logger.info(f"Added {video.source_post_id} to skip list")

            await db.delete(favorite)
            await db.delete(video)
            video_deleted = True
            favorite_cleaned = True
        else:
            await db.delete(favorite)
            favorite_cleaned = True

        await db.commit()

    # Delete video file and sidecar thumbnail if present
    try:
        os.remove(real_path)
        logger.info(f"Deleted library file: {real_path}")
    except OSError as e:
        raise HTTPException(status_code=500, detail=f"Failed to delete file: {e}")

    thumb_path = _thumb_path_for(real_path)
    if os.path.isfile(thumb_path):
        try:
            os.remove(thumb_path)
            logger.info(f"Deleted sidecar thumbnail: {thumb_path}")
        except OSError:
            pass

    return {
        "status": "deleted",
        "filename": filename,
        "relative_path": relative_path,
        "skip_added": skip_added,
        "favorite_cleaned": favorite_cleaned,
        "video_deleted": video_deleted,
    }


@router.get("/stream/{filename:path}")
async def stream_file(filename: str):
    """Stream a local video file with range request support."""
    music_dir = settings.music_videos_path
    real_path = _safe_real_path(filename, music_dir)

    if not os.path.isfile(real_path):
        raise HTTPException(status_code=404, detail=f"File not found: {filename}")

    _, ext = os.path.splitext(filename)
    media_type_map = {
        ".mp4": "video/mp4",
        ".mkv": "video/x-matroska",
        ".webm": "video/webm",
        ".m4v": "video/mp4",
        ".avi": "video/x-msvideo",
        ".mov": "video/quicktime",
    }
    media_type = media_type_map.get(ext.lower(), "video/mp4")

    logger.info(f"Streaming local file: {real_path}")
    return FileResponse(
        path=real_path,
        media_type=media_type,
        filename=os.path.basename(filename),
    )
